import { Inter } from 'next/font/google';

import '@/styles/index.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Kirby + Next.js App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  return (
    <html className="page" lang="en">
      <body className={`page__body ${inter.className}`}>{children}</body>
    </html>
  );
};

export default RootLayout;
